{
 "title": "Resource Optimization Dashboard",
 "description": "Summary metrics about containers running on Kubernetes nodes.\r\n\r\nDashboard was taken from here.  This version does not reqiure you to\r\nsetup the Kubernetes-app plugin. (https://github.com/grafana/kubernetes-app)\r\n\r\nUse this Helm chart to launch Grafana into a Kubernetes cluster.  It will include this dashboard and many more dashboards to give you visibility into the Kubernetes Cluster. (https://github.com/sekka1/cloud-public/tree/master/kubernetes/pods/grafana-helm)",
 "tags": [
  "kubernetes",
  "kubernetes-app"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "node", "query": ".*" },
   { "name": "namespace", "query": ".*" }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage at Cluster Level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\"}[5m])) / sum (machine_cpu_cores) * 100"
    }
   ]
  },
  { "title": "CPU: Percentage of Limit", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "CPU: Percentage of Limit",
   "type": "timeseries",
   "description": "Displays CPU usage as a percentage of the limit given to the container. ",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "100 * (sum(rate(container_cpu_usage_seconds_total{name!~\".*prometheus.*\", container_name!=\"POD\"}[5m])) by (pod_name, container_name) /\nsum(container_spec_cpu_quota{name!~\".*prometheus.*\", container_name!=\"POD\"}/container_spec_cpu_period{name!~\".*prometheus.*\", container_name!=\"POD\"}) by (pod_name, container_name))",
     "legendFormat": "CPU: Percentage of Limit"
    }
   ]
  },
  {
   "title": "Cluster Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Pod Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{}) / sum(kube_node_status_allocatable{resource=\"pods\"})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_name!=\"POD\"}[5m])) by (pod_name, container_name) /\nsum(container_spec_cpu_quota{container_name!=\"POD\"}/container_spec_cpu_period{container_name!=\"POD\"}) by (pod_name, container_name)"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\"}) / sum(kube_node_status_allocatable{resource=\"memory\"})"
    }
   ]
  },
  {
   "title": "Pod Capacity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=~\"pods\"})",
     "legendFormat": "allocatable"
    },
    {
     "expr": "sum(kube_node_status_capacity{resource=~\"pods\"})",
     "legendFormat": "capacity"
    },
    { "expr": "sum(kube_pod_info{})", "legendFormat": "requested" }
   ]
  },
  {
   "title": "CPU Capacity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"cpu\"})",
     "legendFormat": "allocatable"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\"})",
     "legendFormat": "capacity"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\"})",
     "legendFormat": "requested"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_name!=\"POD\"}[5m])) by (container_name, pod_name)",
     "legendFormat": "CPU usage rate"
    }
   ]
  },
  {
   "title": "Memory Capacity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"memory\"})",
     "legendFormat": "allocatable"
    },
    {
     "expr": "sum(kube_node_status_capacity{resource=\"memory\"})",
     "legendFormat": "capacity"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\"})",
     "legendFormat": "requested"
    }
   ]
  },
  {
   "title": "Memory and CPU as Percentage of both Request and Limit",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 }
  },
  {
   "title": "Percentage of CPU Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "round(\n  100 *\n    sum(\n      rate(container_cpu_usage_seconds_total{container_name!=\"POD\"}[5m])\n    ) by (pod, container_name, namespace, slave)\n      /\n    sum(\n      kube_pod_container_resource_requests{container_name!=\"POD\", resource=\"cpu\"}\n    ) by (pod, container_name, namespace, slave)\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Percentage of CPU limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 29 },
   "targets": [
    {
     "expr": "round(\n  100 *\n    sum(\n      rate(container_cpu_usage_seconds_total{container_name!=\"POD\"}[5m])\n    ) by (pod_name, container_name, namespace, slave)\n      /\n    sum(\n      container_spec_cpu_quota{container_name!=\"POD\"} / container_spec_cpu_period{container_name!=\"POD\"}\n    ) by (pod_name, container_name, namespace, slave)\n)",
     "legendFormat": "{{pod_name}} {{namespace}}"
    }
   ]
  },
  {
   "title": "Percentage of Memory Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "round(\n  100 *\n    sum(container_memory_working_set_bytes{container_name!=\"POD\"})\n      /\n    sum(kube_pod_container_resource_requests{container_name!=\"POD\", resource=\"memory\"} > 0)\n)",
     "legendFormat": "Percentage of Memory Request"
    }
   ]
  },
  {
   "title": "Percentage of Memory Limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 29 },
   "targets": [
    {
     "expr": "round(\n  100 *\n    sum(container_memory_working_set_bytes{container_name!=\"POD\"})\n      /\n    sum(container_spec_memory_limit_bytes{container_name!=\"POD\"} > 0)\n)",
     "legendFormat": "Percentage of Memory Limit"
    }
   ]
  },
  {
   "title": "Deployments",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Deployment Replicas - Up To Date",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "kube_deployment_status_replicas{}",
       "legendFormat": "{{deployment}}"
      }
     ]
    },
    {
     "title": "Deployment Replicas",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas{namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Deployment Replicas - Updated",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 16, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas_updated{namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Deployment Replicas - Unavailable",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 20, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=~\"$namespace\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Number Of Nodes",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_info{node=~\"$node\"})"
      }
     ]
    },
    {
     "title": "Nodes Out of Disk",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 8, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_status_condition{condition=\"OutOfDisk\", node=~\"$node\", status=\"true\"})"
      }
     ]
    },
    {
     "title": "Nodes Unavailable",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_spec_unschedulable{node=~\"$node\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Pods",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Pods Running",
     "type": "stat",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Running\"})"
      }
     ]
    },
    {
     "title": "Pods Pending",
     "type": "stat",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Pending\"})"
      }
     ]
    },
    {
     "title": "Pods Failed",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Failed\"})"
      }
     ]
    },
    {
     "title": "Pods Succeeded",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 8, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Succeeded\"})"
      }
     ]
    },
    {
     "title": "Pods Unknown",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Unknown\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Containers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Containers Running",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_running{namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Containers Waiting",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_waiting{namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Containers Terminated",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_terminated{namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Containers Restarts (Last 30 Minutes)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(delta(kube_pod_container_status_restarts{namespace=\"kube-system\"}[30m]))"
      }
     ]
    },
    {
     "title": "CPU Cores Requested by Containers",
     "type": "stat",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=~\"$namespace\", node=~\"$node\"})"
      }
     ]
    },
    {
     "title": "Memory Requested By Containers",
     "type": "stat",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=~\"$namespace\", node=~\"$node\"})"
      }
     ]
    }
   ]
  }
 ]
}